import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import {
  BottomWave,
  BottomWaveMobile,
  TopWave,
  TopWaveMobile,
} from "../assets";

import ImageComponent from "@/components/ImageComponent";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // add weights you need
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-screen h-screen ${montserrat.className} overflow-y-hidden md:overflow-y-scroll relative `}
      >
        <ImageComponent
          dimensions={243}
          src={TopWaveMobile}
          className="absolute top-0 right-0 md:hidden -z-10"
        />
        <ImageComponent
          dimensions={243}
          src={BottomWaveMobile}
          className="absolute bottom-0 left-0 md:hidden -z-10"
        />
        <ImageComponent
          dimensions={418}
          src={TopWaveMobile}
          className="absolute top-0 right-0 hidden md:inline"
        />
        <ImageComponent
          dimensions={418}
          src={BottomWave}
          className="absolute bottom-0 left-0 hidden md:inline"
        />

        <main className="mx-auto max-w-md md:max-w-2xl h-[90vh] pt-[5vh] rounded-md p-2 ">
          {children}
        </main>
      </body>
    </html>
  );
}
