import type { Metadata } from "next";
import "./globals.css";
import {
  BottomWave,
  BottomWaveMobile,
  TopWave,
  TopWaveMobile,
} from "../assets";

import ImageComponent from "@/components/ImageComponent";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen">
        {/* <Image
          src={BottomWaveBackgroundPurple}
          className="absolute bottom-0 z-20  "
          width={418}
          height={418}
          alt="background wave image"
        /> */}
        <ImageComponent
          dimensions={200}
          src={TopWaveMobile}
          className="absolute top-0 right-0 md:hidden -z-10"
        />
        <ImageComponent
          dimensions={200}
          src={BottomWaveMobile}
          className="absolute bottom-0 left-0 md:hidden -z-10"
        />

        <main className="mx-auto max-w-md md:max-w-2xl h-[90vh] my-[5vh] rounded-md p-3">
          {children}
        </main>
      </body>
    </html>
  );
}
