import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  BottomWave,
  BottomWaveMobile,
  TopWave,
  TopWaveMobile,
} from "../assets";

import ImageComponent from "@/components/ImageComponent";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-screen min-h-screen relative ${inter.className} `}>
        <Providers>
          <ImageComponent
            dimensions={243}
            src={TopWaveMobile}
            className="fixed top-0 right-0 lg:hidden -z-10"
          />
          <ImageComponent
            dimensions={243}
            src={BottomWaveMobile}
            className="fixed bottom-0 left-0 lg:hidden -z-10"
          />
          <ImageComponent
            dimensions={418}
            src={TopWave}
            className="fixed top-0 right-0 hidden lg:inline -z-10"
          />
          <ImageComponent
            dimensions={418}
            src={BottomWave}
            className="fixed bottom-0 left-0 hidden lg:inline -z-10"
          />

          <div>
            <Toaster />
          </div>
          <main className="mx-auto max-w-md lg:max-w-2xl min-h-[90vh] pt-[5vh] md:pt-0 rounded-md p-2">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
